# Generated by Django 4.1.2 on 2022-10-15 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
