# Generated by Django 4.1.2 on 2022-10-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
