# Generated by Django 4.1.2 on 2022-10-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='skill',
        ),
    ]
